const API_URL="https://egs-academia-bomberos-api.onrender.com";
let cache={academy:null,sources:null};let activeModule=null,activeTraining=[],activeMeta=null,current=0,correctCount=0,reviewed=0,log=[],timer=null,seconds=0,answered=false,selectedScenario=null;
const SIM_SCENARIOS=[
{id:"house",category:"structural",icon:"⌂",name:"Incendio en vivienda",difficulty:"Inicial–Intermedio",description:"Vivienda con fuego interior, humo, aberturas y víctima.",dispatch:"22:14 h. Humo visible en una vivienda. Posible persona en el interior.",facts:[["Tipo","Vivienda"],["Condición","Noche"],["Dotación","6 bomberos"],["Riesgo","Víctima posible"]],objectives:["Reconocer","Interpretar condiciones","Controlar aberturas","Aplicar agua","Buscar víctima"]},
{id:"apartment",category:"structural",icon:"▦",name:"Incendio en departamento",difficulty:"Intermedio",description:"Compartimentación, ventilación limitada y víctima.",dispatch:"03:38 h. Humo en departamento. Una persona sin localizar.",facts:[["Tipo","Departamento"],["Acceso","Pasillo"],["Ventilación","Limitada"],["Riesgo","Propagación"]],objectives:["Evaluar acceso","Controlar puerta","Enfriar","Ventilar con criterio","Buscar"]},
{id:"warehouse",category:"structural",icon:"▤",name:"Incendio en depósito",difficulty:"Avanzado",description:"Gran volumen, carga combustible y exposiciones.",dispatch:"17:26 h. Columna de humo desde depósito. Personal evacuando.",facts:[["Tipo","Depósito"],["Volumen","Grande"],["Carga","Combustible"],["Riesgo","Propagación"]],objectives:["Reconocer volumen","Proteger exposición","Seleccionar ataque","Controlar propagación"]},
{id:"vehicle_fire",category:"vehicle",icon:"▰",name:"Incendio vehicular",difficulty:"Intermedio",description:"Vehículo liviano con foco en sector motor.",dispatch:"19:02 h. Vehículo en vía pública con fuego visible.",facts:[["Tipo","Vehículo"],["Entorno","Vía pública"],["Foco","Motor"],["Tránsito","Presente"]],objectives:["Asegurar escena","Aislar","Desplegar línea","Enfriar"]},
{id:"vehicle_rescue",category:"vehicle",icon:"✚",name:"Rescate vehicular",difficulty:"Intermedio–Avanzado",description:"Colisión con víctima atrapada y vehículo inestable.",dispatch:"06:41 h. Colisión. Una persona atrapada, consciente.",facts:[["Evento","Colisión"],["Víctima","1"],["Vehículo","Inestable"],["Riesgo","Movimiento"]],objectives:["Evaluar","Aislar riesgos","Estabilizar","Crear acceso","Extricar"]},
{id:"fire_behavior",category:"behavior",icon:"≈",name:"Laboratorio de comportamiento del fuego",difficulty:"Formativo",description:"Cambios de humo, ventilación y transición térmica.",dispatch:"Laboratorio didáctico. Observá indicadores y modificá condiciones.",facts:[["Entorno","Compartimiento"],["Objetivo","Observación"],["Variables","Fuego / humo / aire"],["Modo","Didáctico"]],objectives:["Reconocer indicadores","Comparar ventilación","Visualizar rollover","Visualizar transición"]},
{id:"lines",category:"operations",icon:"↝",name:"Líneas y aplicación de agua",difficulty:"Formativo",description:"Despliegue y uso de línea de ataque con respuesta visual.",dispatch:"Práctica operacional. Prepará una línea y aplicá agua.",facts:[["Recurso","Línea"],["Objetivo","Despliegue"],["Agente","Agua"],["Modo","Práctica"]],objectives:["Desplegar","Seleccionar patrón","Abrir agua","Aplicar sobre foco"]},
{id:"era",category:"operations",icon:"◉",name:"Ingreso con ERA y búsqueda",difficulty:"Intermedio",description:"Ingreso con humo, control de equipo y búsqueda.",dispatch:"Ambiente con humo y visibilidad reducida. Posible víctima.",facts:[["EPP","ERA"],["Visibilidad","Reducida"],["Víctima","Posible"],["Riesgo","Consumo de aire"]],objectives:["Comprobar ERA","Ingresar","Mantener orientación","Buscar","Salir"]}
];
function showScreen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id)?.classList.add("active");window.scrollTo(0,0)}
function goHome(){stopTimer();showScreen("home")}async function api(p){const r=await fetch(API_URL+p);if(!r.ok)throw new Error("HTTP "+r.status);return r.json()}function txt(v){return String(v??"")}
async function boot(){try{const s=await api("/");document.getElementById("apiStatus").textContent=txt(s.status||"EN LÍNEA").toUpperCase();[cache.academy,cache.sources]=await Promise.all([api("/academy/modules"),api("/sources")])}catch(e){document.getElementById("apiStatus").textContent="SERVICIO INICIANDO";console.warn(e)}renderSimCatalog()}
async function openAcademy(){if(!cache.academy)cache.academy=await api("/academy/modules");document.getElementById("academyGrid").innerHTML=cache.academy.modules.map((m,i)=>`<article class="tile clickable" onclick="openModule('${m.id}')"><span class="moduleStatus">MÓDULO ${String(i+1).padStart(2,"0")} · ${txt(m.area)}</span><h2>${txt(m.name)}</h2><p>${txt(m.description)}</p><strong>Explorar módulo →</strong></article>`).join("");showScreen("academy")}
async function openModule(id){activeModule=await api(`/academy/module/${id}`);activeModule._id=id;document.getElementById("moduleTitle").textContent=activeModule.metadata?.module_name||id;document.getElementById("moduleStatus").textContent=(activeModule.metadata?.status||"módulo").toUpperCase();document.getElementById("moduleSourceCount").textContent=`${(activeModule.metadata?.source_ids||[]).length} fuentes`;document.getElementById("moduleQuestionCount").textContent=`${(activeModule.training||[]).length} preguntas disponibles`;document.getElementById("moduleSections").innerHTML=(activeModule.sections||[]).map((s,i)=>`<article class="tile clickable" onclick="openSection(${i})"><span class="moduleStatus">FICHA</span><h2>${txt(s.title)}</h2><p>${txt(s.summary||s.concepts?.join(" · ")||"")}</p><strong>Abrir ficha →</strong></article>`).join("");const b=document.getElementById("moduleTrainingButton");b.style.display=(activeModule.training||[]).length?"inline-block":"none";b.onclick=()=>startTraining(id);showScreen("module")}
function openSection(i){const s=activeModule?.sections?.[i];if(!s)return;document.getElementById("moduleSections").innerHTML=`<article class="tile section-detail"><span class="moduleStatus">FICHA DE ESTUDIO</span><h2>${txt(s.title)}</h2><p style="font-size:1.08rem">${txt(s.summary||s.concepts?.join(" · ")||"Contenido en desarrollo.")}</p>${s.concepts?.length?`<h3>Conceptos clave</h3><ul>${s.concepts.map(c=>`<li>${txt(c)}</li>`).join("")}</ul>`:""}<h3>Fuente doctrinaria</h3><p>${txt(s.source_id||"Material académico")}</p><div class="heroActions"><button class="secondary" onclick="openModule('${activeModule._id}')">← Volver</button>${(activeModule.training||[]).length?`<button class="primary" onclick="startTraining('${activeModule._id}')">Practicar</button>`:""}</div></article>`}
async function showSources(){if(!cache.sources)cache.sources=await api("/sources");document.getElementById("sourceList").innerHTML=cache.sources.sources.map(s=>`<article class="sourceCard"><span class="moduleStatus">${txt(s.status||"FUENTE").toUpperCase()}</span><h3>${txt(s.title)}</h3><p>${txt(s.organization)}</p><p><strong>Rol:</strong> ${txt(s.role)}</p></article>`).join("");showScreen("sources")}
async function searchContent(q){const box=document.getElementById("searchResults");q=q.trim().toLowerCase();if(q.length<2){box.innerHTML="";return}if(!cache.academy)cache.academy=await api("/academy/modules");let rs=[];for(const m of cache.academy.modules){if((m.name+" "+m.description+" "+m.area).toLowerCase().includes(q))rs.push({type:"Módulo",title:m.name,id:m.id,desc:m.description});try{const d=await api(`/academy/module/${m.id}`);for(const s of d.sections||[]){if((s.title+" "+(s.summary||"")).toLowerCase().includes(q))rs.push({type:"Tema",title:s.title,id:m.id,desc:m.name})}}catch(e){}}box.innerHTML=rs.slice(0,10).map(r=>`<article class="tile clickable" onclick="openModule('${r.id}')"><span class="moduleStatus">${r.type}</span><h3>${txt(r.title)}</h3><p>${txt(r.desc)}</p></article>`).join("")}
function renderSimCatalog(f="all"){const g=document.getElementById("simCatalogGrid");if(!g)return;g.innerHTML=SIM_SCENARIOS.filter(s=>f==="all"||s.category===f).map(s=>`<article class="simCard" onclick="selectScenario('${s.id}')"><div class="simIcon">${s.icon}</div><span class="simDifficulty">${s.difficulty}</span><h3>${s.name}</h3><p>${s.description}</p><strong>Ver despacho →</strong></article>`).join("")}
function filterSimCatalog(f,b){document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderSimCatalog(f)}function openSimulatorCatalog(){renderSimCatalog();showScreen("simCatalog")}
function selectScenario(id){selectedScenario=SIM_SCENARIOS.find(s=>s.id===id);document.getElementById("briefTitle").textContent=selectedScenario.name;document.getElementById("briefDescription").textContent=selectedScenario.dispatch;document.getElementById("briefFacts").innerHTML=selectedScenario.facts.map(x=>`<div class="briefFact"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");document.getElementById("briefObjectives").innerHTML=`<ul>${selectedScenario.objectives.map(x=>`<li>${x}</li>`).join("")}</ul>`;document.getElementById("launchScenarioBtn").onclick=()=>launchScenario(id);showScreen("simBrief")}
async function launchScenario(id){showScreen("simBrief");return;document.getElementById("simScenarioTitle").textContent=selectedScenario.name;const e=await loadEGS3D();await e.init();e.loadScenario(id);renderScenarioActions(id);e.start()}
function exitSimulation(){window.EGS3D?.pause?.();showScreen("simulator");Catalog()}
function renderScenarioActions(id){const A={house:[["recognition","Reconocimiento 360°"],["open_access","Abrir acceso"],["open_window","Abrir ventana"],["cooling","Aplicar agua"],["search","Buscar víctima"]],apartment:[["recognition","Reconocimiento"],["control_door","Controlar puerta"],["cooling","Enfriar"],["open_window","Ventilar"],["search","Buscar"]],warehouse:[["recognition","Reconocimiento"],["protect","Proteger exposición"],["cooling","Ataque con agua"],["ventilate","Ventilar"]],vehicle_fire:[["recognition","Asegurar escena"],["isolate","Aislar"],["deploy_line","Desplegar línea"],["cooling","Aplicar agua"]],vehicle_rescue:[["recognition","Evaluar"],["isolate","Aislar riesgos"],["stabilize","Estabilizar"],["access","Crear acceso"],["extricate","Extricar"]],fire_behavior:[["observe","Observar"],["rollover","Rollover"],["ventilate","Aumentar ventilación"],["flashover","Transición térmica"]],lines:[["deploy_line","Desplegar línea"],["select_fog","Patrón niebla"],["select_straight","Chorro pleno"],["cooling","Abrir agua"]],era:[["era_check","Comprobar ERA"],["enter","Ingresar"],["search","Buscar"],["exit","Salir"]]};document.getElementById("simActions").innerHTML=(A[id]||A.house).map(a=>`<button class="actionBtn" onclick="simAction('${a[0]}')">${a[1]}</button>`).join("")}
async function startTraining(id){runTraining(await api(`/academy/module/${id}/training?shuffle=true`),id)}async function startIntegral(){runTraining(await api("/academy/integral?limit=20"),"integral")}
function runTraining(d,id){activeTraining=d.training||[];activeMeta=d.metadata||{};activeMeta._id=id;current=0;correctCount=0;reviewed=0;log=[];seconds=0;answered=false;document.getElementById("trainingTitle").textContent=activeMeta.module_name||"Evaluación integral";showScreen("training");renderStep();startTimer()}
function renderStep(){const q=activeTraining[current];if(!q){finishTraining();return}answered=false;document.getElementById("nextQuestionBtn").classList.add("hidden");document.getElementById("feedback").innerHTML="";document.getElementById("question").textContent=q.question;document.getElementById("stepCounter").textContent=`${current+1}/${activeTraining.length}`;document.getElementById("sourceBadge").textContent=q.source_id||"—";document.getElementById("reviewedCount").textContent=reviewed;const opts=(q.options||[]).slice().sort(()=>Math.random()-.5);document.getElementById("options").innerHTML=opts.map((o,i)=>`<button class="optionBtn" data-i="${i}">${txt(o.text)}</button>`).join("");document.querySelectorAll(".optionBtn").forEach(b=>b.onclick=()=>chooseAnswer(opts[Number(b.dataset.i)],b,opts))}
function chooseAnswer(o,b,opts){if(answered)return;answered=true;reviewed++;const ok=o.status==="correct";if(ok)correctCount++;document.querySelectorAll(".optionBtn").forEach(x=>x.disabled=true);b.classList.add(ok?"selectedCorrect":"selectedWrong");const expected=opts.find(x=>x.status==="correct"),q=activeTraining[current];log.push({n:current+1,question:q.question,answer:o.text,correct:ok,expected:expected?.text||"",source:q.source_id||"—"});document.getElementById("reviewedCount").textContent=reviewed;document.getElementById("feedback").innerHTML=`<div class="feedbackBox ${ok?"correct":""}"><strong>${ok?"Respuesta adecuada":"Respuesta a revisar"}</strong><div>${ok?"Coincide con la respuesta marcada como correcta en el material cargado.":`Respuesta esperada: ${txt(expected?.text||"—")}`}</div><div><b>Fuente:</b> ${txt(q.source_id||"—")}</div></div>`;document.getElementById("nextQuestionBtn").classList.remove("hidden")}
function nextQuestion(){current++;renderStep()}function startTimer(){stopTimer();timer=setInterval(()=>{seconds++;document.getElementById("time").textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`},1000)}function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function finishTraining(){stopTimer();const pct=Math.round(correctCount/Math.max(1,reviewed)*100);document.getElementById("finalScore").textContent=pct;document.getElementById("analysisSummary").innerHTML=`<p>Respuestas revisadas: <strong>${reviewed}</strong></p><p>Adecuadas: <strong>${correctCount}</strong></p><p>Este resultado no crea un perfil personal: sirve para decidir qué repasar.</p>`;document.getElementById("decisionLog").innerHTML=log.map(x=>`<div class="entry"><strong>${x.n}. ${x.correct?"Adecuada":"Revisar"}</strong><p>${txt(x.question)}</p><p>Tu respuesta: ${txt(x.answer)}</p>${x.correct?"":`<p>Esperada: ${txt(x.expected)}</p>`}<p>Fuente: ${txt(x.source)}</p></div>`).join("");showScreen("analysis")}
let egs3dModulePromise=null;async function loadEGS3D(){if(window.EGS3D)return window.EGS3D;if(egs3dModulePromise)return egs3dModulePromise;egs3dModulePromise=import("./simulator.js?v=30").then(()=>window.EGS3D);return egs3dModulePromise}async function setSimulatorQuality(v){(await loadEGS3D()).setQuality(v)}async function reset3DScenario(){(await loadEGS3D()).reset()}async function simAction(a){(await loadEGS3D()).action(a)}async function finish3DSimulation(){(await loadEGS3D()).finish()}
document.addEventListener("DOMContentLoaded",boot);