import * as THREE from "https://esm.sh/three@0.180.0";

const SCENARIOS={
house:{name:"Incendio en vivienda unifamiliar",brief:"Vivienda de una planta con foco en cocina, humo interior y una víctima.",state:{temperature:120,smoke:35,visibility:72,oxygen:20.2,score:100}},
apartment:{name:"Incendio en departamento",brief:"Departamento compartimentado, foco interior y ventilación limitada.",state:{temperature:160,smoke:48,visibility:58,oxygen:19.5,score:100}},
warehouse:{name:"Incendio en depósito",brief:"Depósito con carga combustible, gran volumen y exposición interna.",state:{temperature:190,smoke:42,visibility:64,oxygen:19.9,score:100}},
vehicle_fire:{name:"Incendio vehicular",brief:"Vehículo liviano con fuego en sector motor y producción intensa de humo.",state:{temperature:240,smoke:45,visibility:62,oxygen:20.4,score:100}},
vehicle_rescue:{name:"Rescate vehicular con atrapado",brief:"Colisión de vehículo liviano con víctima atrapada. Requiere asegurar, estabilizar, acceder y extricar.",state:{temperature:28,smoke:0,visibility:100,oxygen:20.9,score:100}},
phenomena:{name:"Laboratorio de fenómenos",brief:"Entorno demostrativo para visualizar cambios bruscos del comportamiento del incendio.",state:{temperature:190,smoke:52,visibility:50,oxygen:18.5,score:100}}
};
const QUALITY={baja:{particles:80,pixel:1},media:{particles:150,pixel:1.1},alta:{particles:260,pixel:1.25}};
let scene,camera,renderer,container,active="house",state={},objects={},fires=[],smoke=[],water=[],running=false,elapsed=0,last=0,quality="media",mode="orbit";
let orbit={drag:false,lx:0,ly:0,yaw:.72,pitch:.48,radius:20},fp={x:0,y:1.65,z:9,yaw:Math.PI,pitch:0},keys={};

function $(id){return document.getElementById(id)}function fmt(s){return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(Math.floor(s%60)).padStart(2,"0")}`}
function mat(c,r=.85){return new THREE.MeshStandardMaterial({color:c,roughness:r})}
function box(parent,size,pos,m,name=""){const x=new THREE.Mesh(new THREE.BoxGeometry(...size),m);x.position.set(...pos);x.name=name;x.castShadow=true;x.receiveShadow=true;parent.add(x);return x}
function log(t){const b=$("simLog");if(!b)return;const d=document.createElement("div");d.textContent=`${fmt(elapsed)} · ${t}`;b.prepend(d);while(b.children.length>14)b.removeChild(b.lastChild)}
function hud(){if($("simClock"))$("simClock").textContent=fmt(elapsed);if($("simTemp"))$("simTemp").textContent=`${Math.round(state.temperature)} °C`;if($("simSmoke"))$("simSmoke").textContent=`${Math.round(state.smoke)} %`;if($("simVisibility"))$("simVisibility").textContent=`${Math.round(state.visibility)} %`;if($("simOxygen"))$("simOxygen").textContent=`${state.oxygen.toFixed(1)} %`;if($("simScore"))$("simScore").textContent=Math.max(0,Math.min(100,Math.round(state.score)));if($("simScenarioTitle"))$("simScenarioTitle").textContent=SCENARIOS[active].name;if($("simBriefing"))$("simBriefing").textContent=SCENARIOS[active].brief}
function fire(pos,s=1){const g=new THREE.Group();g.position.set(...pos);g.scale.setScalar(s);scene.add(g);fires.push(g);for(let i=0;i<14;i++){const f=new THREE.Mesh(new THREE.ConeGeometry(.11+Math.random()*.12,.45+Math.random()*.5,7),new THREE.MeshStandardMaterial({color:i%2?0xff6500:0xffc244,emissive:i%2?0xff2e00:0xff8a00,emissiveIntensity:2.2,transparent:true,opacity:.9}));f.position.set((Math.random()-.5)*1.1,Math.random()*.35,(Math.random()-.5)*.8);g.add(f)}const l=new THREE.PointLight(0xff5b18,6.5,7,2);l.position.y=1;g.add(l)}
function smokeTex(){const c=document.createElement("canvas");c.width=c.height=64;const x=c.getContext("2d"),g=x.createRadialGradient(32,32,3,32,32,30);g.addColorStop(0,"rgba(70,70,70,.5)");g.addColorStop(.6,"rgba(45,45,45,.2)");g.addColorStop(1,"rgba(20,20,20,0)");x.fillStyle=g;x.fillRect(0,0,64,64);return new THREE.CanvasTexture(c)}
function smokeCloud(o,sp){const tex=smokeTex();for(let i=0;i<QUALITY[quality].particles;i++){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,opacity:.2,depthWrite:false}));s.position.set(o[0]+Math.random()*sp[0],o[1]+Math.random()*sp[1],o[2]+Math.random()*sp[2]);const k=.55+Math.random()*1.5;s.scale.set(k,k,k);s.userData.speed=.06+Math.random()*.08;scene.add(s);smoke.push(s)}}
function victim(pos){const v=new THREE.Mesh(new THREE.CapsuleGeometry(.28,.9,4,8),mat(0x1f2327));v.position.set(...pos);v.rotation.z=Math.PI/2;scene.add(v);objects.victim=v}
function vehicle(color=0x8f1f1f){const g=new THREE.Group();scene.add(g),body=mat(color,.65),dark=mat(0x15181a,.8);objects.vehicle=box(g,[4.2,.9,1.9],[0,.85,0],body);box(g,[2.3,.8,1.75],[-.2,1.55,0],body);for(const x of [-1.45,1.45])for(const z of [-.92,.92]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.28,18),dark);w.rotation.x=Math.PI/2;w.position.set(x,.45,z);g.add(w)}return g}
function houseBase(){const g=new THREE.Group();scene.add(g),wall=mat(0xc8b8a2,.96),floor=mat(0x4b4d4f,.98),wood=mat(0x5a3b27,.9);box(g,[12,.25,9],[0,0,0],floor);box(g,[12,3.2,.22],[0,1.7,-4.4],wall);box(g,[.22,3.2,9],[-5.9,1.7,0],wall);box(g,[.22,3.2,9],[5.9,1.7,0],wall);box(g,[3.6,3.2,.22],[-4.1,1.7,4.4],wall);box(g,[2.1,3.2,.22],[-.7,1.7,4.4],wall);box(g,[3.3,3.2,.22],[4.25,1.7,4.4],wall);box(g,[.22,3,5.4],[.8,1.6,-1.3],wall);box(g,[4.8,3,.22],[-3.35,1.6,-1.2],wall);objects.door=box(g,[1.2,2.3,.12],[1.2,1.2,4.28],wood);objects.window=box(g,[2,1.35,.08],[-2.15,1.9,4.28],new THREE.MeshStandardMaterial({color:0x77a9bd,transparent:true,opacity:.45}));box(g,[2.7,.85,1],[-2.2,.55,1],mat(0x51463f));box(g,[2.5,.55,3.1],[-3.5,.42,-2.7],mat(0xb8aaa0));box(g,[3.5,.95,.65],[3.6,.55,-3.7],mat(0x666a6d))}
function clear(){fires=[];smoke=[];water=[];objects={};while(scene.children.length)scene.remove(scene.children[0]);scene.background=new THREE.Color(0x10161c);scene.fog=new THREE.FogExp2(0x2c3236,.018);scene.add(new THREE.HemisphereLight(0xcfe5f7,0x221b17,2));const sun=new THREE.DirectionalLight(0xffefd4,2.7);sun.position.set(-8,14,10);scene.add(sun);const ground=new THREE.Mesh(new THREE.BoxGeometry(40,.25,34),mat(0x283329,1));ground.position.y=-.25;scene.add(ground)}
function build(){
 clear();state=JSON.parse(JSON.stringify(SCENARIOS[active].state));elapsed=0;
 if(active==="house"){houseBase();victim([-3.6,.62,-2.8]);fire([3.8,.35,-3.2],1);smokeCloud([2,1.3,-4],[4.5,2.2,5.2])}
 if(active==="apartment"){houseBase();box(scene,[12,.18,9],[0,3.45,0],mat(0x54575b));victim([-3,.62,-2]);fire([-2.5,.4,1.4],.9);smokeCloud([-4,1.2,-1],[5,2.3,6])}
 if(active==="warehouse"){const g=new THREE.Group();scene.add(g),w=mat(0x8e9499,.92);box(g,[18,.25,12],[0,0,0],mat(0x414448,.98));box(g,[18,5,.25],[0,2.6,-5.8],w);box(g,[.25,5,12],[-8.9,2.6,0],w);box(g,[.25,5,12],[8.9,2.6,0],w);for(let x=-6;x<=6;x+=4)for(let z=-3;z<=2;z+=2.5)box(g,[2.2,2.2,1.4],[x,1.1,z],mat(0x6c4e2f));fire([4,.4,-2],1.3);fire([5.2,.4,-2.4],.8);smokeCloud([0,1.5,-5],[14,3,7])}
 if(active==="vehicle_fire"){vehicle();fire([1.5,.55,0],1);smokeCloud([.8,1.4,-1.5],[4,2.5,3.2])}
 if(active==="vehicle_rescue"){vehicle(0x2f5d8c);objects.vehicle.rotation.y=.18;victim([-.3,1.1,0]);box(scene,[1.6,.25,.8],[2.2,.15,0],mat(0xe8a531))}
 if(active==="phenomena"){const g=new THREE.Group();scene.add(g),w=mat(0xa99c8d,.95);box(g,[10,.25,8],[0,0,0],mat(0x46494c));box(g,[10,3.4,.22],[0,1.8,-3.9],w);box(g,[.22,3.4,8],[-4.9,1.8,0],w);box(g,[.22,3.4,8],[4.9,1.8,0],w);box(g,[3.2,3.4,.22],[-3.4,1.8,3.9],w);box(g,[3.2,3.4,.22],[3.4,1.8,3.9],w);objects.door=box(g,[1.3,2.4,.12],[0,1.25,3.82],mat(0x503627));fire([0,.35,-2.4],.9);smokeCloud([-4,1.4,-3],[8,2.4,6])}
 hud();log("Escenario cargado")
}
function resize(){const r=container.getBoundingClientRect();renderer.setSize(Math.max(320,r.width),Math.max(420,r.height),false);camera.aspect=Math.max(320,r.width)/Math.max(420,r.height);camera.updateProjectionMatrix()}
function orbitCam(){orbit.pitch=Math.max(.14,Math.min(1.25,orbit.pitch));orbit.radius=Math.max(5,Math.min(34,orbit.radius));camera.position.set(orbit.radius*Math.cos(orbit.pitch)*Math.cos(orbit.yaw),1.2+orbit.radius*Math.sin(orbit.pitch),orbit.radius*Math.cos(orbit.pitch)*Math.sin(orbit.yaw));camera.lookAt(0,1.2,0)}
function controls(){renderer.domElement.addEventListener("pointerdown",e=>{if(mode!=="orbit")return;orbit.drag=true;orbit.lx=e.clientX;orbit.ly=e.clientY});renderer.domElement.addEventListener("pointerup",()=>orbit.drag=false);renderer.domElement.addEventListener("pointermove",e=>{if(mode==="orbit"&&orbit.drag){orbit.yaw-=(e.clientX-orbit.lx)*.008;orbit.pitch-=(e.clientY-orbit.ly)*.006;orbit.lx=e.clientX;orbit.ly=e.clientY;orbitCam()}if(mode==="first"&&document.pointerLockElement===renderer.domElement){fp.yaw-=e.movementX*.0025;fp.pitch-=e.movementY*.0022;fp.pitch=Math.max(-1.2,Math.min(1.2,fp.pitch))}});renderer.domElement.addEventListener("wheel",e=>{if(mode!=="orbit")return;e.preventDefault();orbit.radius+=e.deltaY*.012;orbitCam()},{passive:false});renderer.domElement.addEventListener("click",()=>{if(mode==="first")renderer.domElement.requestPointerLock?.()});window.addEventListener("keydown",e=>keys[e.code]=true);window.addEventListener("keyup",e=>keys[e.code]=false);orbitCam()}
function fpMove(dt){if(mode!=="first")return;const speed=3*dt,dir=new THREE.Vector3(Math.sin(fp.yaw),0,Math.cos(fp.yaw)),right=new THREE.Vector3(dir.z,0,-dir.x);if(keys.KeyW){fp.x+=dir.x*speed;fp.z+=dir.z*speed}if(keys.KeyS){fp.x-=dir.x*speed;fp.z-=dir.z*speed}if(keys.KeyA){fp.x-=right.x*speed;fp.z-=right.z*speed}if(keys.KeyD){fp.x+=right.x*speed;fp.z+=right.z*speed}camera.position.set(fp.x,fp.y,fp.z);const look=new THREE.Vector3(Math.sin(fp.yaw)*Math.cos(fp.pitch),Math.sin(fp.pitch),Math.cos(fp.yaw)*Math.cos(fp.pitch));camera.lookAt(camera.position.clone().add(look))}
function waterBurst(){for(let i=0;i<100;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.025,5,4),new THREE.MeshBasicMaterial({color:0x79c7ff}));p.position.set(0,1.2,2.5);p.userData.v=new THREE.Vector3((Math.random()-.5)*.8,.1+Math.random()*.25,-3-Math.random()*2);scene.add(p);water.push(p)}}
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,last?(now-last)/1000:0);last=now;if(running){elapsed+=dt;fires.forEach((g,gi)=>g.children.forEach((f,i)=>{if(f.isMesh)f.scale.y=.8+Math.sin(now*.012+i+gi)*.18+Math.random()*.08}));smoke.forEach(s=>{s.position.y+=s.userData.speed*dt;if(s.position.y>4.8)s.position.y=1.3;s.material.opacity=Math.min(.34,.1+state.smoke/450)});water.forEach((p,i)=>{p.position.addScaledVector(p.userData.v,dt);p.userData.v.y-=1.2*dt;if(p.position.y<0){scene.remove(p);water.splice(i,1)}});if(active!=="vehicle_rescue"){state.temperature=Math.min(850,state.temperature+.3*dt);state.smoke=Math.min(100,state.smoke+.08*dt);state.visibility=Math.max(4,state.visibility-.05*dt);state.oxygen=Math.max(12,state.oxygen-.004*dt)}hud()}fpMove(dt);renderer.render(scene,camera)}
async function init(){container=$("sim3d");if(renderer){resize();return}scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(58,1,.1,100);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.setPixelRatio(Math.min(devicePixelRatio,QUALITY[quality].pixel));container.innerHTML="";container.appendChild(renderer.domElement);controls();build();resize();window.addEventListener("resize",resize);animate(performance.now())}
function start(){running=true;last=performance.now();log("Simulación iniciada")}
function setScenario(v){active=v;build();running=true}
function setCameraMode(v){mode=v;if(v==="first"){fp={x:0,y:1.65,z:9,yaw:Math.PI,pitch:0};log("Primera persona: WASD + mouse")}else{orbitCam();log("Cámara orbital")}}
function setQuality(v){quality=QUALITY[v]?v:"media";renderer.setPixelRatio(Math.min(devicePixelRatio,QUALITY[quality].pixel));build();log("Calidad "+quality)}
function reset(){build();running=true}
function action(a){
 if(a==="recognition"){state.score+=5;log("Reconocimiento completado")}
 if(a==="open_access"){if(objects.door)objects.door.rotation.y=-Math.PI*.48;state.temperature+=28;state.oxygen=Math.min(20.9,state.oxygen+.3);state.smoke=Math.max(0,state.smoke-5);state.visibility=Math.min(100,state.visibility+4);log("Acceso abierto: cambió el flujo")}
 if(a==="open_window"){if(objects.window)objects.window.position.y=3;state.temperature+=38;state.oxygen=Math.min(20.9,state.oxygen+.55);state.smoke=Math.max(0,state.smoke-10);state.visibility=Math.min(100,state.visibility+8);log("Ventana abierta: cambió ventilación")}
 if(a==="ventilate"){state.smoke=Math.max(0,state.smoke-14);state.visibility=Math.min(100,state.visibility+12);state.oxygen=Math.min(20.9,state.oxygen+.45);state.temperature+=24;log("Ventilación ejecutada")}
 if(a==="cooling"){waterBurst();state.temperature=Math.max(40,state.temperature-115);state.smoke=Math.max(0,state.smoke-6);state.visibility=Math.min(100,state.visibility+6);fires.forEach(g=>g.scale.setScalar(.6));state.score+=8;log("Agua aplicada; disminuyó energía térmica")}
 if(a==="search"){if(objects.victim)objects.victim.material.color.set(0xffd166);state.score+=5;log("Búsqueda: víctima localizada")}
 if(a==="protect_exposure"){state.score+=6;log("Exposición protegida")}
 if(a==="isolate"){state.score+=6;log("Riesgos aislados")}
 if(a==="attack_vehicle"){waterBurst();fires.forEach(g=>g.scale.setScalar(.45));state.temperature=Math.max(50,state.temperature-130);state.smoke=Math.max(0,state.smoke-12);log("Ataque al foco vehicular")}
 if(a==="stabilize"){state.score+=8;objects.stabilized=true;log("Vehículo estabilizado")}
 if(a==="access_victim"){state.score+=objects.stabilized?8:-8;log(objects.stabilized?"Acceso creado con vehículo estabilizado":"Acceso creado sin estabilización previa")}
 if(a==="extricate"){if(objects.victim){objects.victim.position.x+=2.2;objects.victim.material.color.set(0xffd166)}state.score+=objects.stabilized?10:-10;log("Extricación ejecutada")}
 if(a==="phen_rollover"){state.temperature=430;state.smoke=72;state.visibility=30;fires.forEach(g=>g.scale.set(1.8,.35,1.8));log("Rollover: llamas en capa superior")}
 if(a==="phen_flashover"){state.temperature=690;state.smoke=90;state.visibility=9;for(let i=0;i<5;i++)fire([-4+i*2,.25,-1+Math.random()*2],.85);log("Flashover: transición rápida a combustión generalizada")}
 if(a==="phen_backdraft"){state.oxygen=15.5;state.smoke=96;state.visibility=5;state.temperature=360;if(objects.door)objects.door.rotation.y=-Math.PI*.48;setTimeout(()=>{for(let i=0;i<6;i++)fire([-3+i*1.2,.3,1.5],1.1);state.temperature=760;hud()},800);log("Demostración educativa: ventilación súbita con gases calientes")}
 if(a==="phen_smoke"){state.smoke=98;state.visibility=3;for(let i=0;i<4;i++)fire([-2+i*1.3,.5,0],.7);state.score-=2;log("Demostración visual de ignición rápida de mezcla de gases")}
 hud()
}
function finish(){running=false;alert(`Simulación finalizada · Puntaje ${Math.max(0,Math.min(100,Math.round(state.score)))}/100 · Tiempo ${fmt(elapsed)}`)}
window.EGS3D={init,start,setScenario,setCameraMode,setQuality,reset,action,finish};
