console.log("EGS 3D v2.1 robusto");
import * as THREE from "./three.module.js";
let scene,camera,renderer,container,running=false,elapsed=0,last=0,activeScenario="house",quality="media";
let objects={},fires=[],smoke=[],water=[],state={};
const INIT={house:[120,35,72,20.2,"Reconocer"],apartment:[155,48,58,19.5,"Evaluar acceso"],warehouse:[190,42,64,19.9,"Reconocer volumen"],vehicle_fire:[230,45,65,20.4,"Asegurar escena"],vehicle_rescue:[28,0,100,20.9,"Evaluar y estabilizar"],fire_behavior:[180,55,48,18.8,"Observar indicadores"],lines:[65,12,90,20.8,"Desplegar línea"],era:[95,68,25,18.9,"Comprobar ERA"]};
const el=id=>document.getElementById(id), mat=c=>new THREE.MeshLambertMaterial({color:c});
function addBox(s,p,c,parent=scene){const x=new THREE.Mesh(new THREE.BoxGeometry(...s),mat(c));x.position.set(...p);parent.add(x);return x}
function log(t){const b=el("simLog");if(!b)return;const d=document.createElement("div");d.textContent=`${fmt(elapsed)} · ${t}`;b.prepend(d)}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(Math.floor(s%60)).padStart(2,"0")}`}
function hud(){if(el("simClock"))el("simClock").textContent=fmt(elapsed);if(el("simTemp"))el("simTemp").textContent=`${Math.round(state.t)} °C`;if(el("simSmoke"))el("simSmoke").textContent=`${Math.round(state.s)} %`;if(el("simVisibility"))el("simVisibility").textContent=`${Math.round(state.v)} %`;if(el("simOxygen"))el("simOxygen").textContent=`${state.o.toFixed(1)} %`;if(el("simObjective"))el("simObjective").textContent=state.obj;if(el("simCondition"))el("simCondition").textContent=state.c}
function clearScene(){while(scene.children.length)scene.remove(scene.children[0]);objects={};fires=[];smoke=[];water=[];scene.background=new THREE.Color(0x182129);scene.fog=new THREE.Fog(0x182129,22,55);scene.add(new THREE.HemisphereLight(0xd9eeff,0x47301d,1.7));const sun=new THREE.DirectionalLight(0xffffff,1.7);sun.position.set(10,16,8);scene.add(sun);addBox([42,.3,34],[0,-.2,0],0x344238)}
function makeFire(p,s=1){const g=new THREE.Group();g.position.set(...p);g.scale.setScalar(s);scene.add(g);fires.push(g);for(let i=0;i<10;i++){const f=new THREE.Mesh(new THREE.ConeGeometry(.2,.9,8),new THREE.MeshBasicMaterial({color:i%2?0xff6a00:0xffc044}));f.position.set((Math.random()-.5)*1.1,.2+Math.random()*.4,(Math.random()-.5)*.8);g.add(f)}const l=new THREE.PointLight(0xff5818,5,8);l.position.y=1;g.add(l)}
function makeSmoke(o=[0,1,0],spread=[5,3,5],count=60){for(let i=0;i<count;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.45,8,6),new THREE.MeshLambertMaterial({color:0x3f474e,transparent:true,opacity:.12}));p.position.set(o[0]+(Math.random()-.5)*spread[0],o[1]+Math.random()*spread[1],o[2]+(Math.random()-.5)*spread[2]);p.userData.speed=.12+Math.random()*.18;scene.add(p);smoke.push(p)}}
function makeVictim(p){const g=new THREE.Group();const torso=new THREE.Mesh(new THREE.CylinderGeometry(.25,.25,.9,10),mat(0x25282b));torso.rotation.z=Math.PI/2;torso.position.y=.45;g.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.22,10,8),mat(0xc69c79));head.position.set(.65,.45,0);g.add(head);g.position.set(...p);scene.add(g);objects.victim=g}
function makeHouse(){const g=new THREE.Group();scene.add(g);const w=0xc3b39e;addBox([12,.25,9],[0,0,0],0x555b60,g);addBox([12,3.3,.25],[0,1.75,-4.4],w,g);addBox([.25,3.3,9],[-5.9,1.75,0],w,g);addBox([.25,3.3,9],[5.9,1.75,0],w,g);addBox([4,3.3,.25],[-4,1.75,4.4],w,g);addBox([4,3.3,.25],[4,1.75,4.4],w,g);objects.door=addBox([1.25,2.35,.18],[1.2,1.2,4.25],0x654328,g);objects.window=addBox([2,1.25,.13],[-2.1,1.9,4.25],0x79a9bf,g)}
function makeCar(c=0x9c2d2d){const g=new THREE.Group();scene.add(g);objects.vehicle=addBox([4.5,.9,2],[0,.7,0],c,g);addBox([2.4,.8,1.8],[-.25,1.5,0],c,g)}
function build(){clearScene();const a=INIT[activeScenario]||INIT.house;state={t:a[0],s:a[1],v:a[2],o:a[3],obj:a[4],c:"Activo"};elapsed=0;
if(activeScenario==="house"){makeHouse();makeVictim([-3.4,.25,-2.6]);makeFire([3.4,.2,-2.8],1.1);makeSmoke([2,1.2,-2.5],[5,3,4],70)}
else if(activeScenario==="apartment"){makeHouse();makeVictim([-3,.25,-2]);makeFire([-2.5,.2,1.2],1.1);makeSmoke([-2,1.1,0],[6,3,5],90)}
else if(activeScenario==="warehouse"){addBox([18,.25,12],[0,0,0],0x5a5d60);for(let x=-6;x<=6;x+=4)for(let z=-3;z<=3;z+=3)addBox([2.2,2.1,1.4],[x,1.05,z],0x765231);makeFire([4,.2,-2],1.5);makeSmoke([2,1.3,-1],[10,4,8],100)}
else if(activeScenario==="vehicle_fire"){makeCar();makeFire([1.5,.25,0],1.2);makeSmoke([1.4,1.1,0],[4,3,3],75)}
else if(activeScenario==="vehicle_rescue"){makeCar(0x315e8a);makeVictim([-.4,.6,0])}
else if(activeScenario==="fire_behavior"){makeHouse();makeFire([0,.2,-2.3],1.15);makeSmoke([0,1.2,-1],[7,3,6],100)}
else if(activeScenario==="lines"){objects.hose=[];for(let i=0;i<7;i++){const h=new THREE.Mesh(new THREE.CylinderGeometry(.09,.09,1.45,10),mat(0xe7c24d));h.rotation.z=Math.PI/2;h.position.set(-4+i*1.35,.12,1.5);h.visible=false;scene.add(h);objects.hose.push(h)}makeFire([6.5,.2,-1.8],1)}
else if(activeScenario==="era"){makeHouse();makeVictim([3,.25,-2]);makeSmoke([0,1,0],[8,3,7],100);objects.era=false}
camera.position.set(15,9,16);camera.lookAt(0,1.1,0);hud();log("Escenario cargado")}
function resize(){if(!renderer||!container)return;const r=container.getBoundingClientRect();const w=Math.max(320,Math.floor(r.width||900)),h=Math.max(300,Math.floor(r.height||600));renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function orbit(){let d=false,px=0,py=0,az=.82,ev=.42,rad=22;const u=()=>{camera.position.set(rad*Math.cos(ev)*Math.cos(az),2+rad*Math.sin(ev),rad*Math.cos(ev)*Math.sin(az));camera.lookAt(0,1.2,0)};renderer.domElement.onpointerdown=e=>{d=true;px=e.clientX;py=e.clientY};renderer.domElement.onpointerup=()=>d=false;renderer.domElement.onpointermove=e=>{if(!d)return;az-=(e.clientX-px)*.007;ev=Math.max(.08,Math.min(1.15,ev-(e.clientY-py)*.006));px=e.clientX;py=e.clientY;u()};renderer.domElement.onwheel=e=>{e.preventDefault();rad=Math.max(6,Math.min(35,rad+e.deltaY*.012));u()};u()}
async function init(){container=el("sim3d");if(!container)throw new Error("No existe #sim3d");if(renderer){resize();return}scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(55,1,.1,100);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.2));container.innerHTML="";container.appendChild(renderer.domElement);orbit();build();resize();window.addEventListener("resize",resize);requestAnimationFrame(animate)}
function animate(n){requestAnimationFrame(animate);const dt=Math.min(.05,last?(n-last)/1000:0);last=n;if(running){elapsed+=dt;fires.forEach(g=>g.children.forEach((f,i)=>{if(f.isMesh)f.scale.y=.85+Math.sin(n*.012+i)*.18}));smoke.forEach(p=>{p.position.y+=p.userData.speed*dt;if(p.position.y>5)p.position.y=.8});for(let i=water.length-1;i>=0;i--){const p=water[i];p.position.addScaledVector(p.userData.v,dt);p.userData.v.y-=1.8*dt;if(p.position.y<0){scene.remove(p);water.splice(i,1)}}hud()}renderer.render(scene,camera)}
function waterBurst(){for(let i=0;i<80;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.035,5,4),new THREE.MeshBasicMaterial({color:0x6ec8ff}));p.position.set(0,1.3,4);p.userData.v=new THREE.Vector3((Math.random()-.5)*.7,.1+Math.random()*.25,-5-Math.random()*2);scene.add(p);water.push(p)}}
function start(){running=true;last=performance.now()} function pause(){running=false} function loadScenario(id){activeScenario=INIT[id]?id:"house";build();running=true} function setQuality(v){quality=v;resize()} function reset(){build();running=true}
function action(a){if(a==="recognition"||a==="observe"){state.obj="Interpretar condiciones";log("Reconocimiento realizado")}if(a==="open_access"){if(objects.door)objects.door.rotation.y=-1.4;state.t+=25;state.o=Math.min(20.9,state.o+.35);log("Acceso abierto")}if(a==="control_door"){if(objects.door)objects.door.rotation.y=-.25;log("Puerta controlada")}if(a==="open_window"||a==="ventilate"){if(objects.window)objects.window.position.y=3.2;state.s=Math.max(0,state.s-9);state.t+=30;log("Ventilación modificada")}if(a==="cooling"){waterBurst();state.t=Math.max(30,state.t-105);fires.forEach(g=>g.scale.multiplyScalar(.68));log("Agua aplicada")}if(a==="search"){if(objects.victim)objects.victim.traverse(x=>{if(x.material?.color)x.material.color.set(0xffd166)});log("Búsqueda realizada")}if(a==="protect"){fires.forEach(g=>g.scale.multiplyScalar(.85));state.c="Exposición protegida"}if(a==="isolate"){state.c="Zona aislada"}if(a==="deploy_line"){objects.hose?.forEach(h=>h.visible=true);log("Línea desplegada")}if(a==="stabilize"){addBox([.7,.35,.8],[-1.7,.18,.95],0xe5a532);addBox([.7,.35,.8],[1.7,.18,.95],0xe5a532);objects.stable=true;state.c="Vehículo estabilizado"}if(a==="access"){state.c=objects.stable?"Acceso creado":"Advertencia: vehículo no estabilizado"}if(a==="extricate"){if(objects.victim)objects.victim.position.set(3,.25,2);state.c="Víctima extricada"}if(a==="rollover"){state.t=430;fires.forEach(g=>g.scale.set(1.8,.45,1.8));state.c="Rollover"}if(a==="flashover"){state.t=690;for(let i=0;i<5;i++)makeFire([-4+i*2,.2,-1+Math.random()*2],.8);state.c="Transición térmica"}if(a==="select_fog"){state.c="Patrón: niebla"}if(a==="select_straight"){state.c="Patrón: chorro pleno"}if(a==="era_check"){objects.era=true;state.c="ERA comprobado"}if(a==="enter"){state.c=objects.era?"Ingreso realizado":"Advertencia: ERA sin comprobar"}if(a==="exit"){state.c="Salida completada"}hud();log(state.c)}
function finish(){running=false;state.c="Finalizado";hud();log("Simulación finalizada")}
window.EGS3D={init,start,pause,loadScenario,setQuality,reset,action,finish};
